### ISSUE TITLE
Build custom database use too much memory

### ISSUE THREAD

**Issue by wsyjh** [liaoherui/StrainScan#12]
Hello！Thank you for the tools you developed. When I build a custom database, It will need about twice as much memory as the number of strains. Is there any way to reduce the amount of memory?

**Comment by liaoherui** [comment]
Hi, thanks for using StrainScan!

As mentioned in our manuscript, the memory and time usage during database construction is still a limitation of our tool when there are a super large number of input strain genomes. However, you may consider using `-e 1` to reduce the memory usage. Nevertheless, if your input has a super large number of strains (e.g. more than 5000 strains), then it could still be a problem.
