### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wangqi0000** [liaoherui/StrainScan#13]
Hello,
when I use the command 1 to identify strains,
command 1: python StrainScan.py -i E.coli-3lr.fastq -d ./download_database/DB_Ecoli -b 1 -o ./test
I got the errors below:
![image](https://github.com/liaoherui/StrainScan/assets/85976600/7a3e3f50-bd44-4300-b0ec-a9cf57726b47)
I don't know what's wrong

By the way, the code that I install StrainScan is:
```
git clone https://github.com/liaoherui/StrainScan.git
cd StrainScan
conda env create -f environment_candidate.yaml
conda activate strainscan
chmod 755 library/jellyfish-linux
chmod 755 library/dashing_s128
```

Thanks for any feedback you might have!

**Comment by liaoherui** [comment]
Hi, thanks for using StrainScan.

It seems this error could be a potential bug due to the identification of low-depth strains. Would you mind sending your test data to us for debugging? Then, we will check the reason and give the solution asap. Thanks!

**Comment by wangqi0000** [comment]
The test data "E.coli-3lr.fastq" is already on Baidu Netdisk.

Baidu Netdisk link: https://pan.baidu.com/s/131vdOx97DERIJwYnK2lZhQ 
Extraction code: khdy

Thanks!!

**Comment by liaoherui** [comment]
Hi, sorry for late reply.

We have fixed the bug in the latest GitHub version. Please re-install StrainScan from the GitHub. And apply it to your data to see whether it works (we have tested the program with the data you provided, and it runs successfully). Thanks!

**Comment by wangqi0000** [comment]
> Hi, sorry for late reply.
> 
> We have fixed the bug in the latest GitHub version. Please re-install StrainScan from the GitHub. And apply it to your data to see whether it works (we have tested the program with the data you provided, and it runs successfully). Thanks!

Thanks for your reply! After re-installing StrainScan, it runs successfully on the test data "Ecoli-3lr.fastq"!
running command: python StrainScan.py -i E.coli-3lr.fastq -d ./download_database/DB_Ecoli -b 1 -o ./test

However, I have another problem. After running strainscan, I got a warning: "Warning: No clusters can be detected!" (even I have used the parameter "-b 1") and only got one output file named "strain_prob.txt" as follows:
![image](https://github.com/liaoherui/StrainScan/assets/85976600/7b6ebd39-9d67-40cb-918c-6194692eb0cb)

That means there is no strain identified, or did I run it wrong again?

**Comment by liaoherui** [comment]
Hi,

I have reviewed your output, and it appears to be reasonable. When you use `-b 1`, this means there could be low-depth strain(s) in your input data. Thus, it's normal to detect no strain clusters. However, when you use the `-b 1` option, the generated "strain_prob.txt" file provides the probabilities of strain clusters existing in your input data. In the screenshot you shared, C33 has a probability of approximately 75%, suggesting that this cluster could potentially be present in your input data. To determine which strains are associated with this cluster, you can refer to the "<Database_Dir>/Cluster_Result/hclsMap_95_recls.txt" file in your database. Usually, the higher the probability, the greater the likelihood of the cluster's presence in your input data.

I hope this explanation clarifies the output for you. If you have any further questions or encounter any other issues, please don't hesitate to ask.

**Comment by wangqi0000** [comment]
Thanks for your explanation! That helps me a lot!

**Comment by wangqi0000** [comment]
> Hi,
> 
> I have reviewed your output, and it appears to be reasonable. When you use `-b 1`, this means there could be low-depth strain(s) in your input data. Thus, it's normal to detect no strain clusters. However, when you use the `-b 1` option, the generated "strain_prob.txt" file provides the probabilities of strain clusters existing in your input data. In the screenshot you shared, C33 has a probability of approximately 75%, suggesting that this cluster could potentially be present in your input data. The final column of this file refers to the strains associated with this cluster. Usually, the higher the probability, the greater the likelihood of the cluster's presence in your input data.
> 
> I hope this explanation clarifies the output for you. If you have any further questions or encounter any other issues, please don't hesitate to ask.

Thanks for your explanation! That helps me a lot!

**Comment by wangqi0000** [comment]
> > Hi,
> > I have reviewed your output, and it appears to be reasonable. When you use `-b 1`, this means there could be low-depth strain(s) in your input data. Thus, it's normal to detect no strain clusters. However, when you use the `-b 1` option, the generated "strain_prob.txt" file provides the probabilities of strain clusters existing in your input data. In the screenshot you shared, C33 has a probability of approximately 75%, suggesting that this cluster could potentially be present in your input data. The final column of this file refers to the strains associated with this cluster. Usually, the higher the probability, the greater the likelihood of the cluster's presence in your input data.
I hope this explanation clarifies the output for you. If you have any further questions or encounter any other issues, please don't hesitate to ask.
> 
Thanks for your explanation! That helps me a lot!

By the way, can I specify the name of the output file? I only see that I can specify the directory where the output file is located

> Hi,
> 
> I have reviewed your output, and it appears to be reasonable. When you use `-b 1`, this means there could be low-depth strain(s) in your input data. Thus, it's normal to detect no strain clusters. However, when you use the `-b 1` option, the generated "strain_prob.txt" file provides the probabilities of strain clusters existing in your input data. In the screenshot you shared, C33 has a probability of approximately 75%, suggesting that this cluster could potentially be present in your input data. The final column of this file refers to the strains associated with this cluster. Usually, the higher the probability, the greater the likelihood of the cluster's presence in your input data.
> 
> I hope this explanation clarifies the output for you. If you have any further questions or encounter any other issues, please don't hesitate to ask.

By the way, can I specify the name of the output file? I only find that I can specify the directory where the output file is located
Thanks!!

**Comment by liaoherui** [comment]
Currently, we don't have that function. But a Python script can achieve that. If you need that function, please email me (heruiliao2-c@my.cityu.edu.hk). Then I can help you with that.
