### ISSUE TITLE
Error for the usage of parameter "-b"

### ISSUE THREAD

**Issue by wangqi0000** [liaoherui/StrainScan#9]
Hello,

when i use the command 1 to identify strains,
command 1: strainscan -i ./E.coli-3lr.fastq -d ./strainscan/DB_Ecoli -o ./strainscan/Test/Ecoli/same-3
i got "Warning: No clusters can be detected!"

So,  i use the command 2 to identify strains, which adds "-b 1"
command 2: strainscan -i ./E.coli-3lr.fastq -d ./strainscan/DB_Ecoli -b 1 -o ./strainscan/Test/Ecoli/same-3
however, i got the error below:

```
usage: StrainScan.py [-h] -i INPUT_FQ -d DB_DIR [-o OUT_DIR] [-k KSIZE]
                     [-l LDEP] [-s MSN]
StrainScan.py: error: unrecognized arguments: -b 1
```
i dont't know what's wrong

Thanks for any feedback you might have!

**Comment by liaoherui** [comment]
Hi, Qi,

Thanks for using StrainScan! If you install StrainScan through Bioconda, then you can run the command below to use the latest GitHub version, which has more new features, including parameter "-b". (Note: you should run the code under the Bioconda environment you have built)

`git clone https://github.com/liaoherui/StrainScan.git`
`cd StrainScan`
`chmod 755 library/jellyfish-linux`
`chmod 755 library/dashing_s128`
`python StrainScan.py -h`
